// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hawjmezkjqcpciclntjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhhd2ptZXpranFjcGNpY2xudGpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MTA1NjIsImV4cCI6MjA2NjI4NjU2Mn0.LoMSusYh0V_AXfQJT17DSXbbrry-rQ9wT9hoiFHy-40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);